language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - travis_retry pip install -r test/requirements.txt
  - travis_retry pip install coveralls
  - travis_retry pip install -e .
script: py.test --cov=pysasl
after_success:
  - coveralls
branches:
  only:
    - master
