language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - travis_retry pip install -r test/requirements.txt
  - travis_retry pip install coveralls
  - travis_retry pip install -e .
script: py.test --cov=pysasl
after_success:
  - coveralls
